fix: error message background is now red
shift72/core-template pull request #164
Opened 2021-07-19 12:33 UTC by PeculiarGoat

https://dev.azure.com/S72/SHIFT72/_workitems/edit/4465

Not sure how I feel about this one.  MaoriNow's problem isn't due to a bug on our end... it's because they are trying to use light _and_ dark themes on the same site and we don't support that.  Now we have an extra colour variable to maintain (and give us a headache on the next red background site) when the previous error colour worked fine and worked with any background colour.  :(

2021-07-19 20:54 UTC, curtisadams28 commented
Having the background and text colour as variables is enough IMO. That way we can easily change it if we run into these edge cases.

2021-07-20 03:46 UTC, PeculiarGoat commented
I think that variables should only exist for common cases... edge cases should be solved with custom css (since they are literally customisations).

2021-07-21 21:07 UTC, curtisadams28 approved these changes
Looks good to me

2021-07-21 23:52 UTC, stajs requested changes
The Maori Now bug was incidental to the discussion - the question being should errors be whatever $body-color might be (e.g. green), or should they be a UX best practice of red?

I think we need variables for both `color` and `background` to give us easy access to change if needed. If maintenance is a concern I don't mind them defaulting to `$body-color` and `$body-bg`, but that doesn't answer the orginal question.

2021-07-21 23:52 UTC, stajs commented on site/styles/_forms.scss
>    color: $body-color;
```suggestion
  color: $error-color;
```

2021-07-21 23:52 UTC, stajs commented on site/styles/_forms.scss
> +    border-color: transparent transparent rgba($error-background, 1) transparent;
Don't like the faint border?

2021-07-21 23:52 UTC, stajs commented on site/styles/_variables.scss
> +$error-background: #dc3545 !default;
```suggestion
$error-color: $body-color !default;
$error-background: $body-bg !default;
```

2021-07-21 23:54 UTC, stajs commented
Let's see if linking works AB#4465

2021-07-25 22:43 UTC, stajs approved these changes

2021-07-27 06:43 UTC, merged