AB#6089 nominations
shift72/core-template pull request #239
Opened 2021-11-30 23:54 UTC by additiverich

[Card here](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Core%20team/Stories/?workitem=6089)
Designs [here](https://zpl.io/a3Jm18y)

- Time to display an items award nominations to complete Phase 1
- Not voting or results yet (Phases 2 & 3)

Homepage
 - carousel displays "in competition" if the title has at least one award nomination
 - meta item thumbnails display (solid) star icon if title has at least one nomination

Film page
 - List of nominations displayed between play / purchase buttons & availability label, and synopsis

2021-12-01 02:13 UTC, PeculiarGoat requested changes
One thing so far!

2021-12-01 02:13 UTC, PeculiarGoat commented on site/templates/common/awards.jet
> +{{block inCompetition()}}
I think one block per file is better.  Having several blocks here means that when I write an override for `awardNominations`, I also need to copy overrides for the other two blocks.

2021-12-01 05:13 UTC, PeculiarGoat requested changes
All looks good except for one issue that I've found:

The star in the top-right corner of a poster clashes with the availability-status component if it has a long string inside.
![image](https://user-images.githubusercontent.com/10665859/144175648-6fe12cd8-c804-4c03-be05-651c9f57f4cc.png)
This example is a real string from the Lithuanian translation file (I had to wiggle the screen size to get it to overlap though).

I'm not invited to the Zeplin workspace so can't see if this was considered by design... but I feel like we should do something about it!

2021-12-01 23:50 UTC, additiverich commented
@PeculiarGoat @matthewthomsonnz This might need a careful once over - I've wrapped the availability status (e.g. "SOLD OUT", "EXPIRED" etc etc) and the icon in a shared wrapper, and applied some flexbox styles to them to get them not to overlap and give them some breathing room. I've tried to be pretty specific with the CSS selectors to avoid any unintended consequences.

2021-12-03 02:32 UTC, PeculiarGoat approved these changes
Not sure how I feel about that text-overflow on the availability-status but it's not a show-stopper.  Everything else looks good to me!

2021-12-05 06:42 UTC, merged