awards categories show winner, translations, latest kibble
shift72/core-template pull request #261
Opened 2022-02-03 03:58 UTC by matthewthomsonnz

This PR:

- updates to the latest kibble which includes award category winner bool
- shows winner_of instead of nominated_for on detail page if IsWinner
- adds winner_of i18n translations

Card here: [AB#6111](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=6111)

2022-02-15 01:23 UTC, matthewthomsonnz commented
@brynyShift72 @l0ud0gg @curtisadams28 pls

2022-02-16 20:57 UTC, l0ud0gg requested changes
couple of missing keys for MX language by the looks. otherwise looks fine. maybe once its released we can deploy latest core template to the https://tvoddemo-addons.shift72.com/ site with all the languages to flick through them all and see them on the frontend.

2022-02-16 20:57 UTC, l0ud0gg commented on site/es_MX.all.json
> +  "awards_winner_of": { "other": "Ganador de" }
looks like mx might be missing the other awards keys? in competition / nominated for

2022-02-17 22:37 UTC, stajs commented
@matthewthomsonnz Just acknowledging the @mention. I wasn't a reviewer but looks fine to me, with just @l0ud0gg comment about MX.

2022-02-18 01:17 UTC, additiverich commented
@l0ud0gg Where are the MX translations coming from?

2022-02-18 03:23 UTC, stajs commented
@additiverich At the risk of seeming ignorant, [they seem to be mostly the same](https://www.getblend.com/blog/is-mexican-a-language/).

2022-02-18 03:24 UTC, stajs approved these changes

2022-02-20 20:45 UTC, merged