Relocate the trailer/wishlist/share buttons beside the play/rent/buy buttons. Adjust styling.
shift72/core-template pull request #265
Opened 2022-02-09 23:49 UTC by matthewthomsonnz

The purpose of this branch is to relocate the trailer, wishlist and share buttons, to beside the purchase and play buttons. In both the carousel, and detail pages.

This is a managable step towards implementing the [refreshed designs](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/62030a7db4a419bfc4e8371e).

Attention has been on consistent spacing between each button (accounting for elements not always present), gutter alignment, element wrapping at smaller viewports, and element vertical alignment.

[AB#5001](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=5001)

2022-02-10 00:08 UTC, matthewthomsonnz commented
Note: This branch has failed css:lint 'selector-max-compound-selectors'. This rule I believe is to encourage utility classes.
This is not possible however because the elements exist in relish. Please let me know if:
1) I can remove the selector-max-compound-selectors rule
or
2) Another way of refactoring the scss

2022-02-12 19:13 UTC, PeculiarGoat commented on site/templates/bundle/buttons.jet
> +    {{yield bundleExtras(class="meta-detail-extras", slug=slug, promoURL=promoURL)}}
Interestingly this doesn't seem to cause any issues ??!!

2022-02-12 19:21 UTC, PeculiarGoat requested changes
Everything looks good except for the dirty hack button:
![image](https://user-images.githubusercontent.com/10665859/153725275-bbd052e1-e0f4-48a5-b7a0-946d5be4c43a.png)

2022-02-12 19:21 UTC, PeculiarGoat commented on site/styles/_buttons.scss
> +    font-weight: 500;
This should be `$font-weight-bold`.

2022-02-14 02:03 UTC, stajs requested changes
Notwithstanding some (u)nits, code looks fine to me. But props to @PeculiarGoat for running it up and noticing the dirty hack button issue to fix, so just that...

2022-02-14 02:04 UTC, stajs commented
For the style lint, I see we are ignoring it in places:

![image](https://user-images.githubusercontent.com/2253814/153787677-ad475189-fcc2-46c4-9337-85628008683b.png)

2022-02-15 01:20 UTC, matthewthomsonnz commented on site/templates/bundle/buttons.jet
> +    {{yield bundleExtras(class="meta-detail-extras", slug=slug, promoURL=promoURL)}}
Yeah need to, and it shouldn't do. This change was required due to the .meta-detail-extras now needing to be in the .meta-detail-buttons div, same as the other detail pages. (Next to the .s72-pricing-buttons etc )

2022-02-15 01:20 UTC, matthewthomsonnz commented on site/styles/_carousel.scss
> +        margin-right: 0rem;
- changed to 0

2022-02-15 01:21 UTC, matthewthomsonnz commented on site/styles/_buttons.scss
> +    font-weight: 500;
- changed to $font-weight-bold

2022-02-15 01:21 UTC, matthewthomsonnz commented on site/styles/_meta-detail.scss
> +        margin-right: 0rem;
- changed to 0

2022-02-15 01:22 UTC, matthewthomsonnz commented
> For the style lint, I see we are ignoring it in places:

- Ignores added

2022-02-15 01:22 UTC, matthewthomsonnz commented
> Everything looks good except for the dirty hack button: ![image](https://user-images.githubusercontent.com/10665859/153725275-bbd052e1-e0f4-48a5-b7a0-946d5be4c43a.png)

- Dirty hack button alignment fixed

2022-02-17 21:03 UTC, stajs approved these changes
:shipit:

2022-02-18 00:55 UTC, PeculiarGoat commented on site/templates/bundle/buttons.jet
> +    {{yield bundleExtras(class="meta-detail-extras", slug=slug, promoURL=promoURL)}}
Yeah I understand why you've moved it here... I'm just surprised it doesn't break down without the import `{{import "./extras.jet"}}` in this file.

2022-02-18 01:06 UTC, merged