Missing translations smit
shift72/core-template pull request #284
Opened 2022-03-07 23:43 UTC by smitsanghvi21

2022-03-09 21:12 UTC, stajs commented on site/nl_BE.all.json
> +  "wcag_skip_links_content": { "other": "Doorgaan naar artike" },
`wcag_skip_links_content` key appears twice.

2022-03-09 21:16 UTC, brynyShift72 requested changes
You've missed some, some translations here may be fine
nl_BE:
`validation_pincode_required`, `shopping_card_existing_expired`,`shopping_card_existing_expiry`, `shopping_card_update_reason_none`, `availability_expired`,  `availability_expires`
no_NO:
`signin_form_error_ip_throttled`,`signin_form_error_account_suspended`, `shopping_discount_applied`, `shopping_error_discount_worn_out`, `shopping_card_existing_expiry`, `shopping_card_existing_expired`, 
`pl_PL`:
`shopping_card_existing_expiry`, `shopping_card_existing_expired` For these 3, you can find the English version in the newest en_AU: `shopping_card_update_reason_none`, `shopping_info_ownership_plan`, `shopping_action_credit`
pt_BR:
`account_form_pin_code_not_set`, `account_form_pin_changed`,`account_form_change_pin`,`user_set_pin_header`,`user_set_pin_button`, `user_submit_pin_heading`, `user_error_wrong_pin_retry`, `user_submit_pin_button`, `user_reset_pin_button`, `validation_pincode2_match`, `validation_pincode2_pattern`, `validation_pincode1_pattern`, `validation_pincode2_required`, `validation_pincode1_required`, `shopping_payment_method_header`, `shopping_payment_method_credit_card`, `shopping_error_stripe_unknown_error`, `shopping_error_payment_complete_failed`, `availability_expires`, `availability_expired`
`pt_PT `Looks good to go

2022-03-13 20:40 UTC, curtisadams28 requested changes
`wcag_skip_links_footer` Is no longer being used so should be removed.

2022-03-13 21:42 UTC, curtisadams28 requested changes

2022-03-13 21:42 UTC, curtisadams28 commented on site/pt_BR.all.json
> +  "shopping_error_plan_expired": { "other": "Este plano não está mais disponível." },
Trailing comma

2022-03-13 22:00 UTC, curtisadams28 approved these changes
LGTM

2022-03-13 22:13 UTC, brynyShift72 approved these changes
LGTM too

2022-03-13 23:04 UTC, merged