Implement the designs  bonus episodes section
shift72/core-template pull request #326
Opened 2022-04-28 01:15 UTC by matthewthomsonnz

The main purpose of this PR is to 

Designs:
- [Mobile](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142ba83fd3fd250f50e6216)
- [Tablet](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142baeda13fc726053e405a)
- [Desktop](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6142bb2eb8582a2b4c2c93ee)

2022-05-02 02:52 UTC, brynyShift72 reviewed
Seems the designs have the Bonus/Episodes title below the poster image, Currently looks as if its dependent on the size of the synopsis. eg
Zeplin:
![image](https://user-images.githubusercontent.com/69442193/166178546-d4a2665f-a89b-4922-b05a-453c536d2669.png)
This Branch:
![image](https://user-images.githubusercontent.com/69442193/166178577-55fdc3e5-1c80-4715-9ea1-6b84070e022f.png)
Looks like the current implementation has it below the poster.

2022-05-02 07:52 UTC, PeculiarGoat requested changes
I feel like this is a good opportunity build something better from scratch rather than bending the existing mess to do something new.

Given that the bonus and episode are _almost_ identical, they can be extracted into a single shared jet.  And switching to grid should greatly simplify handling of the different layouts at different breakpoints.  And gap can take care of all of the padding and margins in a much simpler way.

2022-05-02 07:52 UTC, PeculiarGoat commented on site/styles/_meta-detail.scss
> +  @extend .clearfix;
No Bootstrap plz!

2022-05-03 23:11 UTC, l0ud0gg commented
a couple of nit picks, otherwise looks good (other than the others feedback);

1. thumbnail seems to have rounded corners on top but square on the bottom 
2. play button not centered

![Screen Shot 2022-05-04 at 11 07 35 AM](https://user-images.githubusercontent.com/10949384/166587556-fc0dceab-c358-4afa-86db-c3e77df6105f.png)

2022-05-03 23:12 UTC, l0ud0gg approved these changes
If the others are happy, mine are nit picks, otherwise im happy :)

2022-05-04 03:10 UTC, matthewthomsonnz commented
> Seems the designs have the Bonus/Episodes title below the poster image, Currently looks as if its dependent on the size of the synopsis. eg Zeplin: ![image](https://user-images.githubusercontent.com/69442193/166178546-d4a2665f-a89b-4922-b05a-453c536d2669.png) This Branch: ![image](https://user-images.githubusercontent.com/69442193/166178577-55fdc3e5-1c80-4715-9ea1-6b84070e022f.png) Looks like the current implementation has it below the poster.

@brynyShift72 I could raise this with design but am pretty confident this is fine, even welcomed. The goal of the element switcher for example was to bring the episodes/bonuses up as high as possible, as some clients were complaining these sections are too low.

2022-05-04 03:11 UTC, matthewthomsonnz commented on site/styles/_meta-detail.scss
> +  @extend .clearfix;
- removed in favor of css grid

2022-05-04 03:12 UTC, matthewthomsonnz commented
> a couple of nit picks, otherwise looks good (other than the others feedback);
> 
> 1. thumbnail seems to have rounded corners on top but square on the bottom
> 2. play button not centered
> 
> ![Screen Shot 2022-05-04 at 11 07 35 AM](https://user-images.githubusercontent.com/10949384/166587556-fc0dceab-c358-4afa-86db-c3e77df6105f.png)

Cheers Louis
- play button centered
- border radius bottom fixed

2022-05-04 03:37 UTC, matthewthomsonnz commented
> I feel like this is a good opportunity build something better from scratch rather than bending the existing mess to do something new.
> 
> Given that the bonus and episode are _almost_ identical, they can be extracted into a single shared jet. And switching to grid should greatly simplify handling of the different layouts at different breakpoints. And gap can take care of all of the padding and margins in a much simpler way.

- Changed approach to grid
- Merged bonus_item/episode_item into single new block (called sub_item)

I concede grid is actually pretty good

2022-05-04 03:41 UTC, smitsanghvi21 reviewed
Not sue from where is this image coming from. Or is it showing some part of the landscape image?

 https://staging-store-kibble.shift72.com/admin/#/film/48/images

<img width="1181" alt="Screen Shot 2022-05-04 at 9 09 03 AM" src="https://user-images.githubusercontent.com/13471681/166620246-43853104-8355-43e1-adeb-dc7316675a4d.png">

2022-05-04 06:03 UTC, PeculiarGoat requested changes
Looking pretty good!

I'm wondering if we need to handle cases where clients upload oddly sized images:
![image](https://user-images.githubusercontent.com/10665859/166629816-f539144c-1379-4719-af8c-d6a67a588984.png)

Looks even stranger on mobile:
![image](https://user-images.githubusercontent.com/10665859/166629884-ac2c094c-c916-4730-ae35-54816c99082f.png)

2022-05-04 23:45 UTC, matthewthomsonnz commented
> Not sue from where is this image coming from. Or is it showing some part of the landscape image?
> 
> https://staging-store-kibble.shift72.com/admin/#/film/48/images
> 
> <img alt="Screen Shot 2022-05-04 at 9 09 03 AM" width="1181" src="https://user-images.githubusercontent.com/13471681/166620246-43853104-8355-43e1-adeb-dc7316675a4d.png">

Hey @smitsanghvi21 that ones unrelated. Pretty sure thats some old custom classification image work. I cleared that image once by copying the admin film save query into postman.

2022-05-05 02:29 UTC, matthewthomsonnz commented on site/templates/items/sub_item.jet
> +  <div class="poster-container">
Do we need to though? It feels like complexity for no purpose

2022-05-05 02:31 UTC, matthewthomsonnz commented
> Looking pretty good!
> 
> I'm wondering if we need to handle cases where clients upload oddly sized images: ![image](https://user-images.githubusercontent.com/10665859/166629816-f539144c-1379-4719-af8c-d6a67a588984.png)
> 
> Looks even stranger on mobile: ![image](https://user-images.githubusercontent.com/10665859/166629884-ac2c094c-c916-4730-ae35-54816c99082f.png)

Cheers. Sure did look weird nice catch.

- Have showed Bex in person and added a fix

2022-05-05 15:39 UTC, PeculiarGoat commented on site/templates/items/sub_item.jet
> +  <div class="poster-container">
No probably not... it's just that jet changes are easier to review than CSS changes 😛

2022-05-05 15:50 UTC, PeculiarGoat reviewed
Good fix!

Do we care about things getting bent out of shape when there is too much content?
![image](https://user-images.githubusercontent.com/10665859/166962504-7c025581-bac1-4384-ad10-0219c0eaf0ef.png)

Probably a question for design team.

2022-05-06 01:52 UTC, brynyShift72 reviewed
@matthewthomsonnz Was there a take away/ answer yet from design on the Bonus/Episode placement in regards to its position relative to the poster?

2022-05-06 02:44 UTC, matthewthomsonnz commented
> Good fix!
> 
> Do we care about things getting bent out of shape when there is too much content? 
> 
> Probably a question for design team.

Cheers. I showed Bex and she said that's fine as long as we maintain the same size margin under the heading

2022-05-06 02:46 UTC, matthewthomsonnz commented
> @matthewthomsonnz Was there a take away/ answer yet from design on the Bonus/Episode placement in regards to its position relative to the poster?

Ah I forgot about that. Yes! There was. I'll have to add a wrapper to the main content with min height.

2022-05-08 01:18 UTC, matthewthomsonnz commented
@brynyShift72 I've added a wrapper with min height. It works for the typical layout, but not if abnormal size poster or sponsor logo. We will have to remove this rule and redo whole detail page with CSS grid instead in a future PR.

2022-05-09 11:44 UTC, PeculiarGoat commented
@matthewthomsonnz I don't see the point of that wrapper... I would prefer to not have it.  IMO the designs show that the Bonus Content/Episodes header should be relative to the See More button (always 42px below it) and not relative to the poster.

2022-05-09 21:57 UTC, matthewthomsonnz commented
> @matthewthomsonnz I don't see the point of that wrapper... I would prefer to not have it. IMO the designs show that the Bonus Content/Episodes header should be relative to the See More button (always 42px below it) and not relative to the poster.

@PeculiarGoat Yeah I agree - reverted. Definitely appears relative in the designs, and it can't be treated as an afterthought we'll do it properly in another PR with grid

2022-05-09 22:14 UTC, stajs commented
It looks like @l0ud0gg has deferred to the others, so if @smitsanghvi21 @brynyShift72 can review and give @PeculiarGoat a break!

2022-05-10 12:01 UTC, PeculiarGoat requested changes
Nearly there!

2022-05-11 02:24 UTC, matthewthomsonnz commented on site/styles/_meta-detail.scss
> +.episode-item {
- replaced bonus-item and episode item with sub-item
- moved .sub-item scss into a new file

2022-05-11 02:24 UTC, matthewthomsonnz commented on site/styles/_meta-detail.scss
> +  .poster {
- css moved

2022-05-11 09:52 UTC, PeculiarGoat approved these changes
Nice work @matthewthomsonnz!  It will be much easier to add/change things for bonus/episodes in the future now!

2022-05-11 23:34 UTC, merged