Ab#7900/fix wording for no trial period
shift72/core-template pull request #336
Opened 2022-05-09 00:41 UTC by josejibin

[ADO](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=7900)

Zero is condsidered as plural in i18 lib. So existing logic won't work.

2022-05-09 01:33 UTC, additiverich commented
@josejibin Is the implication that if the user is using (for example) Arabic, which treats "0" as a "zero" plurality, there won't be a translation for the `shopping_price_plan_note` if Count is 0?

2022-05-09 09:43 UTC, PeculiarGoat requested changes
Relish is able to fall back on `other` if the desired plurality isn't there, but Kibble doesn't... it will just return the key.

Even though `shopping_price_plan_note` is a translation for a Relish component, I think we should start beating these translation files into shape and enforce the plural rules before we move the data to the database.

2022-05-09 09:43 UTC, PeculiarGoat commented on site/ja_JP.all.json
>      "one": "24時間の無料トライアルが終了した後、.Intervalごとに{{ .Interval }}",
Japanese only supports [other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L15).

2022-05-09 09:43 UTC, PeculiarGoat commented on site/lt_LT.all.json
>      "one": "{{ .Interval }} kas .Intervalas pasibaigus 24 valandų nemokamam bandomajam laikotarpiui.",
Lithuanian  supports [one, few, many, and other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L164).

2022-05-09 09:43 UTC, PeculiarGoat commented on site/ru_RU.all.json
>      "one": "{{ .Interval }} каждые после окончания 24-часового бесплатного пробного периода.",
Russian requires [one, few, many, and other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L176).

2022-05-09 09:43 UTC, PeculiarGoat commented on site/sr_SR.all.json
>      "one": "Наплаћује се сваки {{ .Interval }} након завршетка бесплатног пробног периода од 24 сата.",
Serbian requires [one, few, and other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L108).

2022-05-09 09:43 UTC, PeculiarGoat commented on site/uk_UA.all.json
>      "one": "Стягується кожні {{ .Interval }} після закінчення 24-годинної безкоштовної пробної версії.",
Ukranian supports [one, few, many, other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L176).

2022-05-09 09:43 UTC, PeculiarGoat commented on site/zh_TW.all.json
>      "one": "24 小時免費試用期結束後， {{ .Interval }}收費一次。",
Chinese only supports [other](https://github.com/nicksnyder/go-i18n/blob/0dc1626d56435e9d605a29875701721c54bc9bbd/i18n/language/codegen/plurals.xml#L15).

2022-05-09 22:08 UTC, stajs commented
@josejibin please request review from delivery team to auto-assign reviewers.

![image](https://user-images.githubusercontent.com/2253814/167506778-be627480-90e4-4713-90fa-151d82d9f758.png)

2022-05-11 10:08 UTC, PeculiarGoat commented on site/ar_LB.all.json
> -    "zero": "اتهم كل {{ .Interval }} .",
`shopping_price_plan_note` for Arabic is still missing `zero`.  Everything else is looking good though!

2022-05-12 02:17 UTC, PeculiarGoat commented on site/ar_LB.all.json
> -    "zero": "اتهم كل {{ .Interval }} .",
@josejibin I'll approve once you add a `zero` plurality to `shopping_price_plan_note`!

2022-05-12 08:17 UTC, additiverich commented
(Just looping in some more delivery team members)

2022-05-13 03:45 UTC, PeculiarGoat approved these changes
Nice 👍

2022-05-16 01:33 UTC, curtisadams28 approved these changes

2022-05-16 01:43 UTC, stajs commented on site/ar_LB.all.json
> -    "zero": "اتهم كل {{ .Interval }} .",
@PeculiarGoat Perhaps we bake in some plurality validation in the API?

2022-05-16 03:55 UTC, merged

2022-05-16 04:00 UTC, stajs requested changes
Yikes, I know you've just merged and I've come in way late with the review.