AB#7900: fix translations
shift72/core-template pull request #344
Opened 2022-05-16 04:57 UTC by josejibin

Continuation from the [PR](https://github.com/shift72/core-template/pull/336)

* Fix the suggestions from the [PR](https://github.com/shift72/core-template/pull/336)
* Remove the whitespace from mustaches variables

2022-05-17 02:02 UTC, PeculiarGoat approved these changes
Nice work!  Sorry I missed this on the previous PR... reviewing translations is mind-numbing!

2022-05-17 09:03 UTC, stajs approved these changes
Thanks for tidying those up! Only had one question but not a blocker for me.

2022-05-17 22:50 UTC, l0ud0gg requested changes
Mostly good. left a few comments around duplicate .Interval's etc.

2022-05-17 22:50 UTC, l0ud0gg commented on site/ca_ES.all.json
> +    "one": "Es {{.Interval}} cada .Interval després que finalitzi la prova gratuïta de 24 hores.",
this has .Interval in there twice, with the second not in moustaches. not sure if thats intended or not?

2022-05-17 22:50 UTC, l0ud0gg commented on site/da_DK.all.json
> +    "one": "{{.Interval}} automatisk hvert .Interval",
this has .Interval in there twice, with the second not in moustaches. not sure if thats intended or not?

2022-05-17 22:50 UTC, l0ud0gg commented on site/et_ET.all.json
> +    "one": "{{.Interval}} iga .intervalli järel pärast 24-tunnise tasuta prooviperioodi lõppu.",
is .intervalli supposed to be here?

2022-05-17 22:50 UTC, l0ud0gg commented on site/et_ET.all.json
> +    "other": "{{.Interval}} iga .Intervall ."
is .Intervall supposed to be here?

2022-05-17 22:50 UTC, l0ud0gg commented on site/no_NO.all.json
> +    "one": "{{.Interval}} automatisk hver .Interval",
Is there supposed to be a second .Interval here?

2022-05-17 22:50 UTC, l0ud0gg commented on site/pl_PL.all.json
> +    "other": "Wypróbuj bezpłatną {{.Count}} próbną programu .Count!"
is there supposed to be a second .Count in here?

2022-05-17 22:54 UTC, stajs commented on site/it_IT.all.json
> +    "other": "L&#39;acquisto dell&#39;abbonamento è andato a buon fine. Ora sei iscritto a {{.Title}} ."
Nope! It was only if you were going to rely on the HTML entities.

2022-05-18 05:53 UTC, l0ud0gg approved these changes
one nit pick comment. otherwise all good 👍

2022-05-18 05:53 UTC, l0ud0gg commented on site/et_ET.all.json
>      "other": "{{.Interval}} iga .intervalli järel pärast {{.Count}} päeva tasuta prooviperioodi lõppu."
sorry one more .intervallii here in the :other

2022-05-18 06:04 UTC, merged