Add unqiue class to tagline
shift72/core-template pull request #345
Opened 2022-05-16 22:42 UTC by brynyShift72

AB#8005 Stemmed from Sakka request to hide runtime on front end and keep other taglines. Would be nice to add to core template.
All meta items were previously the same class so hiding an individual one required either
1. Removing metadata from /admin page (requires configuration to skip publishing validation)
2. Removing specific logic from `tagline.jet`

Notes: I think some styles are being pulled through relish with an `!important` property eg, `display: inline !important;`, meaning that making these items disappear would require a `display: none !important;` (Maybe there is a better way to do this)

Would also be open to better class names

2022-05-17 02:15 UTC, PeculiarGoat commented
@brynyShift72 this would be more readable if you ditched the `meta-item-tagline-` from those new classes.  You can probably live without the `-divider` suffix too.  Thoughts?

2022-05-17 22:53 UTC, l0ud0gg approved these changes
good call. looks good to me.

2022-05-18 10:05 UTC, stajs commented
I like the idea and looking at the file has prompted some refactor thoughts, so I took a run at it also but including @PeculiarGoat's points about class name brevity.

2022-05-22 23:04 UTC, curtisadams28 commented
I wonder if hiding the parts of the tagline would be better done with uber configs?

2022-05-22 23:24 UTC, stajs commented
Why not both? If uber, changes still have to come through us and wait until we build out admin UI. This will be available once self-service CSS is out.

2022-05-22 23:48 UTC, curtisadams28 commented
Good point.

2022-06-13 01:19 UTC, curtisadams28 requested changes
I'm just going to leave this here so it doesn't show up in PR shaming. Guessing we're going to use Shannons [PR](https://github.com/shift72/core-template/pull/347)?

2022-06-28 04:14 UTC, PeculiarGoat commented
@brynyShift72 bump!

2022-06-29 22:32 UTC, closed without merging