full width carousel background
shift72/core-template pull request #83
Opened 2021-01-10 22:51 UTC by curtisadams28

ADO Card (https://dev.azure.com/S72/SHIFT72/_boards/board/t/Delivery%20team/Stories/?workitem=2706)

2021-01-10 22:57 UTC, curtisadams28 commented on site/templates/collection/carousel_item.jet
> +        <div class="carousel-item-image" style="background-image: url({{item.Images.Carousel}})"></div>
Ideally, I would have used `object-fit: cover;` on the image but it isn't supported in IE11. The tradeoff with this method is that you don't get the alt tag. Alternatively, I discovered that you can use `background-image` on a `<img>` tag but I'm not sure if that is good practice?

2021-01-10 23:02 UTC, gscragg requested changes
I would like a good reason why `s72-image` is no longer being used.

2021-01-13 00:53 UTC, gscragg commented
> I would like a good reason why `s72-image` is no longer being used.

And I ask this because using an `s72-image` component gives us the power to change the image that is rendered or make other decisions about the image before rendering it.

Our carousel component does try to resize itself based on the images dimensions: https://github.com/indiereign/shift72-web/blob/master/src/ui/carousel/carousel.component.js#L10

2021-01-13 02:12 UTC, stajs commented
@gscragg New PR here https://github.com/shift72/core-template/pull/86

@curtisadams28 This PR should be abandoned? The carousel `imageSizeRatio` - is that what you've done in the CSS calcs of the new PR (maybe continue discussion there)?

2021-01-13 21:50 UTC, closed without merging