Custom button live event
shift72/core-template pull request #99
Opened 2021-05-03 05:17 UTC by l0ud0gg

2021-05-03 05:41 UTC, PeculiarGoat requested changes
Looks good apart from that one thing which is my bad :p

2021-05-03 05:41 UTC, PeculiarGoat commented on site/static/js/custom-owned-button.component.js
> +    return this.app.itemLimitService.get(slug).then(limit => {
Sorry just noticed this item limit call... it can be removed!

2021-05-05 05:30 UTC, PeculiarGoat approved these changes

2021-05-05 07:01 UTC, stajs reviewed
Sorry, I thought I had saved the review last time - not sure what happened.

2021-05-05 21:53 UTC, l0ud0gg commented on site/static/js/custom-owned-button.component.js
> +    return state.loaded && state.isOwned && (
commited your suggestion, churrrr

2021-05-05 21:56 UTC, merged